name: Merge Daily PQ Files to PQs_2025.json

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure package.json for ES modules
        run: |
          echo '{ "type": "module" }' > package.json

      - name: Merge daily files into PQs_2025.json
        run: node scripts/merge-days.js

      - name: Commit merged file to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git stash --include-untracked
          git pull origin main --rebase || {
            echo "❌ Merge failed. Aborting to prevent corrupted commit."
            exit 1
          }
          git stash pop || echo "ℹ️ No stash to apply"
          git add data/PQs_2025.json || echo "No merged file to add"
          git commit -m "Manual merge of daily files into PQs_2025.json" || echo "Nothing to commit"
          git push origin HEAD
